name: Generate Android release keystore (one-time)

# Run manually from Actions → Generate Android release keystore
on:
  workflow_dispatch:

jobs:
  gen-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed for artifacts)
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create keystore (non-interactive)
        run: |
          # === EDITABLE VALUES (optional) ===
          # If you'd like different password / alias, change these values before you run.
          KEYSTORE_PASSWORD="MyKeystorePass123!"
          KEY_PASSWORD="$KEYSTORE_PASSWORD"
          KEY_ALIAS="release_alias"
          DNAME="CN=Your Name, OU=Dev, O=YourOrg, L=City, ST=State, C=IN"
          # ===================================

          echo "Creating keystore with alias=$KEY_ALIAS"

          # Generate keystore non-interactively
          keytool -genkeypair -v \
            -keystore release.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -alias "$KEY_ALIAS" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "$DNAME"

          # Create Base64 representation (single-line) for GitHub Secret
          base64 release.keystore > release.keystore.base64

          # Show short info (NOT the base64) so you know file exists
          ls -l release.keystore release.keystore.base64
          echo "Keystore generated. Please download the artifacts from this run."

      - name: Upload keystore artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keystore-artifacts
          path: |
            release.keystore
            release.keystore.base64
